version: 0.2
env:
  variables:
    stage: "deploy stage"

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn build:${stage}
  post_build:
    commands:
      - aws s3 sync ./public s3://aws-495476032358-squard-frontend-prod/
      - aws cloudfront create-invalidation --distribution-id EWTJR4OXGOMDO --paths '/*'

