export const AWS_APPSYNC_GRAPHQL_ENDPOINT =
  process.env.GATSBY_AWS_APPSYNC_GRAPHQL_ENDPOINT || ''
export const AWS_APPSYNC_API_KEY = process.env.GATSBY_AWS_APPSYNC_API_KEY || ''
export const AWS_COGNITO_USERPOOL_ID =
  process.env.GATSBY_AWS_COGNITO_USERPOOL_ID || ''
export const AWS_COGNITO_USERPOOL_CLIENT_ID =
  process.env.GATSBY_AWS_COGNITO_USERPOOL_CLIENT_ID || ''
export const AWS_COGNITO_USERPOOL_DOMAIN =
  process.env.GATSBY_AWS_COGNITO_USERPOOL_DOMAIN || ''
